require'symbols-outline'.setup {
    highlight_hovered_item = true,
    show_guides = true,
    auto_preview = true,
    position = 'right',
    show_numbers = false,
    show_relative_numbers = false,
    show_symbol_details = true,
    keymaps = {
        close = {'<Esc>', 'q'},
        goto_location = {'<CR>', '<2-LeftMouse>'},
        focus_location = 'o',
        hover_symbol = '<C-space>',
        rename_symbol = '<space>rn',
        code_actions = {'a', '<C-f>'},
        fold = {'h', 'zc'},
        unfold = {'l', 'zo'},
        fold_all = 'zC',
        unfold_all = 'zO',
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
        File = {icon = '', hl = 'TSURI'},
        Module = {icon = '', hl = 'TSNamespace'},
        Namespace = {icon = '', hl = 'TSNamespace'},
        Package = {icon = '', hl = 'TSNamespace'},
        Class = {icon = '𝓒', hl = 'TSType'},
        Method = {icon = 'ƒ', hl = 'TSMethod'},
        Property = {icon = '', hl = 'TSMethod'},
        Field = {icon = '', hl = 'TSField'},
        Constructor = {icon = '', hl = 'TSConstructor'},
        Enum = {icon = 'ℰ', hl = 'TSType'},
        Interface = {icon = 'ﰮ', hl = 'TSType'},
        Function = {icon = '', hl = 'TSFunction'},
        Variable = {icon = '', hl = 'TSConstant'},
        Constant = {icon = '', hl = 'TSConstant'},
        String = {icon = '𝓐', hl = 'TSString'},
        Number = {icon = '#', hl = 'TSNumber'},
        Boolean = {icon = '⊨', hl = 'TSBoolean'},
        Array = {icon = '', hl = 'TSConstant'},
        Object = {icon = '⦿', hl = 'TSType'},
        Key = {icon = '🔐', hl = 'TSType'},
        Null = {icon = 'NULL', hl = 'TSType'},
        EnumMember = {icon = '', hl = 'TSField'},
        Struct = {icon = '𝓢', hl = 'TSType'},
        Event = {icon = '🗲', hl = 'TSType'},
        Operator = {icon = '+', hl = 'TSOperator'},
        TypeParameter = {icon = '𝙏', hl = 'TSParameter'}
    }
}

require'nvpunk.util.keymapper'.nkeymap(
    'go', '<cmd>SymbolsOutline<cr>', 'פּ Symbols Outline'
)
